"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import {
  fetchPapers,
  generateReviewMatrix,
  createResearchNote,
  getErrorMessage,
  type PaperListItem,
  type ReviewMatrixResponse,
  type ReviewMatrixRow,
} from "@/lib/api";

const COLUMNS: Array<{ key: keyof ReviewMatrixRow; label: string }> = [
  { key: "problem", label: "问题" },
  { key: "method", label: "方法" },
  { key: "evidence", label: "证据" },
  { key: "metric", label: "指标/结果" },
  { key: "limitation", label: "局限" },
  { key: "future_work", label: "未来工作" },
];

function shortTitle(title: string): string {
  return title.length > 36 ? `${title.slice(0, 36)}...` : title;
}

function matrixToMarkdown(result: ReviewMatrixResponse): string {
  const header = [
    "Paper",
    "Problem",
    "Method",
    "Evidence",
    "Metric/Result",
    "Limitation",
    "Future Work",
    "Source Chunk IDs",
  ];
  const rows = result.rows.map((row) => [
    row.paper_title,
    row.problem,
    row.method,
    row.evidence,
    row.metric,
    row.limitation,
    row.future_work,
    row.source_chunk_ids.join(", "),
  ]);
  const escapeCell = (value: string) => value.replace(/\|/g, "/").replace(/\s+/g, " ").trim();
  return [
    `Generated by: ${result.generated_by}`,
    "",
    `| ${header.join(" | ")} |`,
    `| ${header.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(escapeCell).join(" | ")} |`),
  ].join("\n");
}

export default function ReviewMatrix() {
  const [papers, setPapers] = useState<PaperListItem[]>([]);
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set());
  const [maxChunks, setMaxChunks] = useState(8);
  const [loadingPapers, setLoadingPapers] = useState(true);
  const [loadingMatrix, setLoadingMatrix] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<ReviewMatrixResponse | null>(null);
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    fetchPapers()
      .then((res) => setPapers(res.papers.filter((paper) => paper.status === "completed")))
      .catch((err) => setError(getErrorMessage(err, "加载论文列表失败")))
      .finally(() => setLoadingPapers(false));
  }, []);

  const selectedPapers = useMemo(
    () => papers.filter((paper) => selectedIds.has(paper.id)),
    [papers, selectedIds],
  );

  function togglePaper(id: number) {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function selectAll() {
    setSelectedIds(new Set(papers.map((paper) => paper.id)));
  }

  function clearSelection() {
    setSelectedIds(new Set());
  }

  async function handleGenerate() {
    setLoadingMatrix(true);
    setError(null);
    setResult(null);
    try {
      const ids = selectedIds.size > 0 ? Array.from(selectedIds) : undefined;
      setResult(await generateReviewMatrix(ids, maxChunks));
    } catch (err) {
      setError(getErrorMessage(err, "生成综述表失败"));
    } finally {
      setLoadingMatrix(false);
    }
  }

  async function copyMarkdown() {
    if (!result) return;
    try {
      await navigator.clipboard.writeText(matrixToMarkdown(result));
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1600);
    } catch {
      setError("复制失败，请手动选择表格内容复制");
    }
  }

  async function saveMatrixNote() {
    if (!result) return;
    try {
      await createResearchNote({
        title: `文献综述表：${result.total_papers} 篇论文`,
        content: matrixToMarkdown(result),
        note_type: "review_matrix",
        source: { source_kind: "review_matrix" },
        tags: ["review", "matrix"],
      });
      setSaved(true);
      window.setTimeout(() => setSaved(false), 1600);
    } catch (err) {
      setError(getErrorMessage(err, "保存综述表到笔记失败"));
    }
  }

  return (
    <div className="space-y-6">
      <section className="rounded-xl border border-gray-100 bg-white p-5 shadow-sm">
        <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <h2 className="text-lg font-semibold text-gray-800">选择论文</h2>
            <p className="mt-1 text-sm text-gray-500">
              不选择论文时默认使用全部已完成论文。当前矩阵为启发式提取，不调用真实模型。
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              onClick={selectAll}
              disabled={papers.length === 0}
              className="rounded-lg border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs font-medium text-blue-700 hover:bg-blue-100 disabled:opacity-50"
            >
              全选已完成
            </button>
            <button
              type="button"
              onClick={clearSelection}
              disabled={selectedIds.size === 0}
              className="rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs font-medium text-gray-600 hover:bg-gray-50 disabled:opacity-50"
            >
              清空选择
            </button>
          </div>
        </div>

        {loadingPapers ? (
          <p className="text-sm text-gray-500">正在加载论文列表...</p>
        ) : papers.length === 0 ? (
          <div className="rounded-lg border border-dashed border-gray-200 p-4 text-center">
            <p className="text-sm text-gray-500">暂无已完成论文</p>
            <Link href="/papers" className="mt-2 inline-block text-sm text-blue-600 hover:underline">
              前往上传
            </Link>
          </div>
        ) : (
          <div className="flex flex-wrap gap-2">
            {papers.map((paper) => (
              <button
                key={paper.id}
                type="button"
                onClick={() => togglePaper(paper.id)}
                className={`rounded-full border px-3 py-1.5 text-xs font-medium transition-colors ${
                  selectedIds.has(paper.id)
                    ? "border-blue-600 bg-blue-600 text-white"
                    : "border-gray-300 bg-white text-gray-600 hover:border-blue-400"
                }`}
              >
                {shortTitle(paper.title)}
              </button>
            ))}
          </div>
        )}

        <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center">
          <label className="flex items-center gap-2 text-sm text-gray-600">
            每篇最多扫描片段
            <select
              value={maxChunks}
              onChange={(event) => setMaxChunks(Number(event.target.value))}
              className="rounded-md border border-gray-300 px-2 py-1 text-sm"
            >
              {[4, 8, 12, 16, 20].map((value) => (
                <option key={value} value={value}>{value}</option>
              ))}
            </select>
          </label>
          <button
            type="button"
            onClick={handleGenerate}
            disabled={loadingPapers || loadingMatrix || papers.length === 0}
            className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
          >
            {loadingMatrix ? "生成中..." : "生成综述表"}
          </button>
          <span className="text-xs text-gray-500">
            当前选择 {selectedPapers.length || papers.length} 篇论文
          </span>
        </div>
      </section>

      {error && (
        <div className="rounded-lg border border-red-200 bg-red-50 p-3">
          <p className="text-sm text-red-700">{error}</p>
        </div>
      )}

      {result && (
        <section className="rounded-xl border border-gray-100 bg-white p-5 shadow-sm">
          <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <h2 className="text-lg font-semibold text-gray-800">结构化综述表</h2>
              <p className="mt-1 text-sm text-gray-500">
                共 {result.total_papers} 篇论文，生成方式：{result.generated_by}
              </p>
            </div>
            <button
              type="button"
              onClick={copyMarkdown}
              className="rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs font-medium text-gray-600 hover:bg-gray-50"
            >
              {copied ? "已复制" : "复制 Markdown"}
            </button>
            <button
              type="button"
              onClick={saveMatrixNote}
              className="rounded-lg border border-blue-200 bg-white px-3 py-1.5 text-xs font-medium text-blue-600 hover:bg-blue-50"
            >
              {saved ? "已保存" : "存为笔记"}
            </button>
          </div>

          {result.warnings.length > 0 && (
            <div className="mb-4 rounded-lg border border-yellow-200 bg-yellow-50 p-3">
              <p className="text-xs font-medium text-yellow-700">生成提示</p>
              <ul className="mt-1 list-inside list-disc text-xs text-yellow-700">
                {result.warnings.map((warning) => (
                  <li key={warning}>{warning}</li>
                ))}
              </ul>
            </div>
          )}

          <div className="overflow-x-auto">
            <table className="min-w-[980px] border-collapse text-left text-xs">
              <thead>
                <tr className="border-b border-gray-200 bg-gray-50 text-gray-600">
                  <th className="w-44 px-3 py-2 font-semibold">论文</th>
                  {COLUMNS.map((column) => (
                    <th key={column.key} className="px-3 py-2 font-semibold">{column.label}</th>
                  ))}
                  <th className="w-36 px-3 py-2 font-semibold">来源</th>
                </tr>
              </thead>
              <tbody>
                {result.rows.map((row) => (
                  <tr key={row.paper_id} className="border-b border-gray-100 align-top">
                    <td className="px-3 py-3 font-medium text-blue-700">
                      <Link href={`/papers/${row.paper_id}`} className="hover:underline">
                        {row.paper_title}
                      </Link>
                    </td>
                    {COLUMNS.map((column) => (
                      <td key={column.key} className="px-3 py-3 text-gray-700">
                        {String(row[column.key])}
                      </td>
                    ))}
                    <td className="px-3 py-3">
                      <div className="flex flex-col gap-1">
                        {row.sources.map((source) => (
                          <Link
                            key={source.chunk_id}
                            href={`/papers/${source.paper_id}#chunk-${source.chunk_id}`}
                            className="text-blue-600 hover:underline"
                            title={source.text_excerpt}
                          >
                            chunk #{source.chunk_index}
                          </Link>
                        ))}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      )}
    </div>
  );
}
